module.exports = {
  color: {
    SETTING_SLOW_VERSION: false,
    SETTING_BG_COLOR: 0x55FFFF,
    SETTING_FACE_COLOR: 0x000000,
    SETTING_FACE_MIX_WITH_BACKGROUND: false,
    SETTING_LINE_COLOR: 0x55FFFF,
    SETTING_LINE_MIX_WITH_BACKGROUND: false,
    SETTING_SPLIT_LINE_COLORS: false,
    SETTING_BACK_LINE_COLOR: 0x55FFFF,
    SETTING_SIDE_LINE_COLOR: 0x55FFFF
  },
  bw: {
    SETTING_SLOW_VERSION: false,
    SETTING_BG_COLOR: 0x000000,
    SETTING_FACE_COLOR: 0x000000,
    SETTING_FACE_MIX_WITH_BACKGROUND: false,
    SETTING_LINE_COLOR: 0xFFFFFF,
    SETTING_LINE_MIX_WITH_BACKGROUND: false,
    SETTING_SPLIT_LINE_COLORS: false,
    SETTING_BACK_LINE_COLOR: 0xFFFFFF,
    SETTING_SIDE_LINE_COLOR: 0xFFFFFF
  }
};
