module.exports = {
  color: {
    SETTING_SLOW_VERSION: false,
    SETTING_BG_COLOR: 0x000000,
    SETTING_FACE_COLOR: 0x000000,
    SETTING_SPLIT_FACE_COLORS: false,
    SETTING_FACE_COLOR_1: 0x000000,
    SETTING_FACE_COLOR_2: 0x000000,
    SETTING_FACE_COLOR_3: 0x000000,
    SETTING_FACE_COLOR_4: 0x000000,
    SETTING_FACE_MIX_WITH_BACKGROUND: false,
    SETTING_LINE_COLOR: 0x00AAFF,
    SETTING_LINE_MIX_WITH_BACKGROUND: false,
    SETTING_SPLIT_LINE_COLORS: true,
    SETTING_BACK_LINE_COLOR: 0xAAAA55,
    SETTING_SIDE_LINE_COLOR: 0xFF55AA,
    SETTING_THICK_LINES: false
  },
  bw: {
    SETTING_SLOW_VERSION: false,
    SETTING_BG_COLOR: 0x000000,
    SETTING_FACE_COLOR: 0x000000,
    SETTING_SPLIT_FACE_COLORS: false,
    SETTING_FACE_COLOR_1: 0x000000,
    SETTING_FACE_COLOR_2: 0x000000,
    SETTING_FACE_COLOR_3: 0x000000,
    SETTING_FACE_COLOR_4: 0x000000,
    SETTING_FACE_MIX_WITH_BACKGROUND: false,
    SETTING_LINE_COLOR: 0xFFFFFF,
    SETTING_LINE_MIX_WITH_BACKGROUND: false,
    SETTING_SPLIT_LINE_COLORS: false,
    SETTING_BACK_LINE_COLOR: 0xFFFFFF,
    SETTING_SIDE_LINE_COLOR: 0xFFFFFF,
    SETTING_THICK_LINES: false
  }
};
